<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>shade</string>
	</array>
	<key>name</key>
	<string>Shade</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^(var|default)[\t ]+([^\t ]+)[\t ]*=</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.shade</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.variable.shade</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolatedstrings</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.shade</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.shade</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.namespace.shade</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(use)[\t ]+(namespace)[\t ]*=[\t ]*(.+)[\t ]*$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.shade</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.shade</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.assembly.shade</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(use)[\t ]+(assembly)[\t ]*=[\t ]*(.+)[\t ]*$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.shade</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.shade</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.namespace.shade</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(use)[\t ]+(import)[\t ]*=[\t ]*(.+)[\t ]*$</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(functions|for|each)\b</string>
			<key>name</key>
			<string>keyword.control.shade</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\#[^\t ]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.shade</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>meta.function.shade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#depsandvars</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolatedstrings</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(macro)[\t ]*name=['"]([^\t ]+)['"]</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.shade</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.macro.shade</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n?$</string>
			<key>name</key>
			<string>meta.macro.shade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#depsandvars</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolatedstrings</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^[\t ]*([_A-Za-z][_A-Za-z0-9\-]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.invoke</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>meta.command.shade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#depsandvars</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolatedstrings</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^[\t ]*(\-)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.shade</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>section.embedded.source.shade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#csharp</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@?([a-zA-Z0-9]+)?)(\s[a-zA-Z0-9]+)?(
|
)?(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.shade</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.shade</string>
				</dict>
			</dict>
			<key>comments</key>
			<string>Simple multi-line code section</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.shade</string>
				</dict>
			</dict>
			<key>name</key>
			<string>section.embedded.source.shade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(@?([a-zA-Z0-9]+)?)(\s[a-zA-Z0-9]+)?(
|
)?(\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.shade</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.shade</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.shade</string>
						</dict>
					</dict>
					<key>name</key>
					<string>section.embedded.source.cshtml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#csharp</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#csharp</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@[a-zA-Z0-9]+)(\s?)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>section.embedded.begin.shade</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.shade</string>
				</dict>
			</dict>
			<key>comments</key>
			<string>Covers single line Razor tags</string>
			<key>end</key>
			<string>(\n|\s)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.source.shade</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.namespace.source.shade</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(([a-zA-Z0-9]+)(\.)?)+?</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#csharp</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>csharp</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.cs</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolatedstrings</string>
				</dict>
			</array>
		</dict>
		<key>depsandvars</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\.[_A-Za-z][_A-Za-z0-9]*)</string>
					<key>name</key>
					<string>storage.modifier.csharp</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>([_A-Za-z][_A-Za-z0-9]*)\=</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.shade</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$|[\t ]+</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolatedstrings</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>interpolatedstrings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\$\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.shade</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.shade</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.interpolated.shade</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.cs</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.shade</string>
	<key>uuid</key>
	<string>4f902f1e-9ac6-497d-a110-6d450bfd5b0b</string>
</dict>
</plist>
